# Generated by Django 4.2.7 on 2026-04-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_customerbehaviorevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerbehaviorevent',
            new_name='customer_be_custome_a816b6_idx',
            old_name='recommender_cust_prod_idx',
        ),
    ]
